app:
  build: .
  # env_file: .env
  environment:
    RAILS_ENV: $RAILS_ENV
  links:
    - db
  ports:
    - 3000:3000

db:
  image: postgres:9.4.5
  volumes:
   - casein-sample-postgres:/var/lib/postgresql/data
